version: '3.9'
services:
  php8: 
    build: ./back_end_php
    volumes:  
      - './wellplayed_back_end_v2/:/var/www/html'
    ports:
      - 8080:8000
  mysql:
    container_name: wellplayed_back_end_db
    build: ./back_end_mysql
    volumes:  
      - './docker/data:/var/lib/mysql'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
            default:
                aliases:
                    - 'app.m2i'